### ISSUE TITLE
com a propriedade testMode false, no modulo do componente, permite utilizar cartões teste que não são da iugu

### ISSUE THREAD

**Issue by fehrabelo** [PetersonFonsec/ngx-iugu#7]

**Comment by PetersonFonsec** [comment]
Olá @fehrabelo, tudo bem ?

Não, a propriedade **testMode** diz se o **token** gerado é um token de uma transação real ou de teste, se o seu projeto  esta no ambiente de desenvolvimento e você quer testar diferentes cenários, você precisa passar **true** nessa propriedade e utilizar os cartões de teste da Iugu pois assim não será gerado nenhuma cobrança.

Em produção onde todos os tokens forem para transações reais você passa **false**.
